/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Data */
        post: operations["upload_data_api_data_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Samples */
        get: operations["get_samples_api_data_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Sample */
        post: operations["load_sample_api_data_samples__sample_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/{data_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data */
        get: operations["get_data_api_data__data_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Registry */
        get: operations["get_registry_api_models_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/compatible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Compatible */
        post: operations["get_compatible_api_models_compatible_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train */
        post: operations["train_api_training_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/{training_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_api_training__training_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prediction/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_prediction_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_results_comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_predict_api_prediction_predict_post */
        Body_predict_api_prediction_predict_post: {
            /** Training Id */
            training_id: string;
            /** Model Key */
            model_key: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_data_api_data_upload_post */
        Body_upload_data_api_data_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Target Column */
            target_column?: string | null;
            /**
             * Has Target
             * @default true
             */
            has_target: boolean;
        };
        /** CategoricalDistribution */
        CategoricalDistribution: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "categorical";
            /** Categories */
            categories: string[];
            /** Counts */
            counts: number[];
            /**
             * Other Count
             * @default 0
             */
            other_count: number;
        };
        /** ColumnSummary */
        ColumnSummary: {
            /** Name */
            name: string;
            /**
             * Dtype
             * @enum {string}
             */
            dtype: "numeric" | "categorical";
            /** Is Target */
            is_target: boolean;
            /** Missing Count */
            missing_count: number;
            /** Missing Pct */
            missing_pct: number;
            /** Unique Count */
            unique_count: number;
            /** Distribution */
            distribution: components["schemas"]["NumericDistribution"] | components["schemas"]["CategoricalDistribution"];
            /** Mean */
            mean?: number | null;
            /** Std */
            std?: number | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Median */
            median?: number | null;
            /** Top Value */
            top_value?: string | null;
            /** Top Value Freq */
            top_value_freq?: number | null;
        };
        /** ComparisonEntry */
        ComparisonEntry: {
            /** Training Id */
            training_id: string;
            /** Model Key */
            model_key: string;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** ComparisonModelRef */
        ComparisonModelRef: {
            /** Training Id */
            training_id: string;
            /** Model Key */
            model_key: string;
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** Models */
            models: components["schemas"]["ComparisonModelRef"][];
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /** Common Metrics */
            common_metrics: string[];
            /** Models */
            models: components["schemas"]["ComparisonEntry"][];
        };
        /** CompatibilityRequest */
        CompatibilityRequest: {
            /** Data Id */
            data_id: string;
        };
        /** CompatibilityResponse */
        CompatibilityResponse: {
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "classification" | "regression" | "clustering";
            /** Compatible */
            compatible: components["schemas"]["ModelSummary"][];
            /** Incompatible */
            incompatible: components["schemas"]["IncompatibleModelSummary"][];
        };
        /** DataProfileResponse */
        DataProfileResponse: {
            /** Data Id */
            data_id: string;
            /** Source */
            source: string;
            /** N Rows */
            n_rows: number;
            /** N Columns */
            n_columns: number;
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "classification" | "regression" | "clustering";
            /** Target Column */
            target_column?: string | null;
            /** Columns */
            columns: components["schemas"]["ColumnSummary"][];
            class_imbalance?: components["schemas"]["ImbalanceInfo"] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Error
             * @default true
             * @constant
             */
            error: true;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImbalanceInfo */
        ImbalanceInfo: {
            /** Is Imbalanced */
            is_imbalanced: boolean;
            /** Class Counts */
            class_counts: {
                [key: string]: number;
            };
            /** Message */
            message?: string | null;
        };
        /** IncompatibleModelSummary */
        IncompatibleModelSummary: {
            /** Key */
            key: string;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
            /** Default Hyperparameters */
            default_hyperparameters: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
        };
        /** ModelSummary */
        ModelSummary: {
            /** Key */
            key: string;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
            /** Default Hyperparameters */
            default_hyperparameters: {
                [key: string]: unknown;
            };
        };
        /** ModelTrainSpec */
        ModelTrainSpec: {
            /** Model Key */
            model_key: string;
            /** Hyperparameters */
            hyperparameters?: {
                [key: string]: unknown;
            };
        };
        /** NumericDistribution */
        NumericDistribution: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "numeric";
            /** Bin Edges */
            bin_edges: number[];
            /** Counts */
            counts: number[];
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Training Id */
            training_id: string;
            /** Model Key */
            model_key: string;
            /** Model Type */
            model_type: string;
            /** N Samples */
            n_samples: number;
            /** Predictions */
            predictions: unknown[];
            /** Probabilities */
            probabilities?: number[][] | null;
        };
        /** RegistryResponse */
        RegistryResponse: {
            /** Models */
            models: components["schemas"]["ModelSummary"][];
        };
        /** SampleDatasetInfo */
        SampleDatasetInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "classification" | "regression" | "clustering";
            /** N Rows */
            n_rows: number;
            /** N Columns */
            n_columns: number;
        };
        /** SampleListResponse */
        SampleListResponse: {
            /** Samples */
            samples: components["schemas"]["SampleDatasetInfo"][];
        };
        /** TrainRequest */
        TrainRequest: {
            /** Data Id */
            data_id: string;
            /** Models */
            models: components["schemas"]["ModelTrainSpec"][];
            /**
             * Test Size
             * @default 0.2
             */
            test_size: number;
        };
        /** TrainResponse */
        TrainResponse: {
            /** Training Id */
            training_id: string;
            /** Data Id */
            data_id: string;
            /** Test Size */
            test_size: number;
            /** Results */
            results: components["schemas"]["TrainedModelResponse"][];
        };
        /** TrainedModelResponse */
        TrainedModelResponse: {
            /** Model Key */
            model_key: string;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Hyperparameters */
            hyperparameters: {
                [key: string]: unknown;
            };
            /** Training Time Seconds */
            training_time_seconds: number | null;
            /** N Features */
            n_features: number;
            /** Feature Importance */
            feature_importance: {
                [key: string]: number;
            } | null;
            /** Visualization Data */
            visualization_data: {
                [key: string]: unknown;
            } | null;
            /** Plot Data */
            plot_data: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_data_api_data_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_data_api_data_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataProfileResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_samples_api_data_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    load_sample_api_data_samples__sample_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataProfileResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_api_data__data_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                data_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataProfileResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_api_models_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_compatible_api_models_compatible_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_api_training_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_training__training_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_prediction_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_api_prediction_predict_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_results_comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
